---
book_repo: pivotal-cf/docs-book-observability-data-store
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'edge'

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

- repository:
    name: pivotal-cf/docs-observability-data-store
    ref: '1.0'
  directory: observability-data-store/1-0
  subnav_template: observability_1_0_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.0
    changelog_href: https://docs.pivotal.io/observability-data-store/1-0/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Observability Data Store for PCF
    search_placeholder: Search Observability Data Store for PCF
    url_prefix: observability-data-store/1-0
    local_product_version: 1.0
    local_header_links: []